// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

interface ICore {
    event FeeCollected(uint256 amount);
    event OwnershipTransferred(
        address indexed previousOwner,
        address indexed newOwner
    );
    event Paused(address account);
    event PeakWhitelisted(address indexed peak);
    event Unpaused(address account);

    function accumulatedFee() external view returns (uint256);

    function bBTC() external view returns (address);

    function bBtcToBtc(uint256 bBtc)
        external
        view
        returns (uint256 btc, uint256 fee);

    function badgerGovernance() external view returns (address);

    function btcToBbtc(uint256 btc)
        external
        view
        returns (uint256 bBtc, uint256 fee);

    function collectFee() external;

    function feeSink() external view returns (address);

    function guardian() external view returns (address);

    function guestList() external view returns (address);

    function mint(
        uint256 btc,
        address account,
        bytes32[] calldata merkleProof
    ) external returns (uint256);

    function mintFee() external view returns (uint256);

    function owner() external view returns (address _owner);

    function pause() external;

    function paused() external view returns (bool _paused);

    function peakAddresses(uint256) external view returns (address);

    function peaks(address) external view returns (uint8);

    function pricePerShare() external view returns (uint256);

    function redeem(uint256 bBtc, address account) external returns (uint256);

    function redeemFee() external view returns (uint256);

    function setConfig(
        uint256 _mintFee,
        uint256 _redeemFee,
        address _feeSink
    ) external;

    function setGuardian(address _guardian) external;

    function setGuestList(address _guestList) external;

    function setPeakStatus(address peak, uint8 state) external;

    function totalSystemAssets() external view returns (uint256 totalAssets);

    function transferOwnership(address newOwner) external;

    function unpause() external;

    function whitelistPeak(address peak) external;
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[{"internalType":"address","name":"_bBTC","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"FeeCollected","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"account","type":"address"}],"name":"Paused","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"peak","type":"address"}],"name":"PeakWhitelisted","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"address","name":"account","type":"address"}],"name":"Unpaused","type":"event"},{"inputs":[],"name":"accumulatedFee","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"bBTC","outputs":[{"internalType":"contract IbBTC","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"bBtc","type":"uint256"}],"name":"bBtcToBtc","outputs":[{"internalType":"uint256","name":"btc","type":"uint256"},{"internalType":"uint256","name":"fee","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"badgerGovernance","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"btc","type":"uint256"}],"name":"btcToBbtc","outputs":[{"internalType":"uint256","name":"bBtc","type":"uint256"},{"internalType":"uint256","name":"fee","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"collectFee","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"feeSink","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"guardian","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"guestList","outputs":[{"internalType":"contract BadgerGuestListAPI","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"btc","type":"uint256"},{"internalType":"address","name":"account","type":"address"},{"internalType":"bytes32[]","name":"merkleProof","type":"bytes32[]"}],"name":"mint","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"mintFee","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"_owner","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"pause","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"paused","outputs":[{"internalType":"bool","name":"_paused","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"peakAddresses","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"peaks","outputs":[{"internalType":"enum Core.PeakState","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"pricePerShare","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"bBtc","type":"uint256"},{"internalType":"address","name":"account","type":"address"}],"name":"redeem","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"redeemFee","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_mintFee","type":"uint256"},{"internalType":"uint256","name":"_redeemFee","type":"uint256"},{"internalType":"address","name":"_feeSink","type":"address"}],"name":"setConfig","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_guardian","type":"address"}],"name":"setGuardian","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"_guestList","type":"address"}],"name":"setGuestList","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"peak","type":"address"},{"internalType":"enum Core.PeakState","name":"state","type":"uint8"}],"name":"setPeakStatus","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"totalSystemAssets","outputs":[{"internalType":"uint256","name":"totalAssets","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"unpause","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"peak","type":"address"}],"name":"whitelistPeak","outputs":[],"stateMutability":"nonpayable","type":"function"}]
*/